update grafana-cloud-metrics.yaml to install and configure grafana 3.…
rackspace-orchestration-templates/grafana pull request #23
Opened 2016-11-01 20:45 UTC by VinnyQ

# What

Update grafana-cloud-metrics.yaml to install and configure grafana 3.1.1 to integrate with blueflood rackspace metrics.

# Why

Because, progress.

# How

Removing instructions for previous version of grafana and add instruction to install grafana 3.1.1 from binary package, add blueflood plugin as a datasource, install graphite-api, install blueflood-graphite-api-finder, all proxied by nginx, and use grafana api to setup the datasource and admin user.

# Test

Create a custom heat template in Reach - Orchestration (mycloud.rackspace.com) using the content of the yaml, spin up a stack using it with the correct auth info, and verify grafana3 is installed and working.

2016-11-01 20:46 UTC, VinnyQ commented
@wolfdancer shane, here's the new version of the grafana yaml that will install and configure grafana 3.1.1 to work with blueflood.  Give it a try!

@goru97 please review also if you have a chance.  Thanks!

2016-11-01 20:50 UTC, VinnyQ commented
@wolfdancer do note that I moved the previous version (grafana 1.8.1) to a totally new file:  grafana-cloud-metrics-1.8.1.yaml.

Once we merge, any links to the grafana-cloud-metrics.yaml will see and use the grafana 3.1.1 install instead.  To test from this PR, click on the "View" button in the diff view for the grafana-cloud-metrics.yaml file.

2016-11-01 20:51 UTC, VinnyQ commented
Oh great news about this version, we get to completely remove the dependencies on the blueflood git repo (https://github.com/rackerlabs/blueflood.git) since we no longer need the config.js file from it (all grafana plugin config are done via the blueflood datasource and the grafana http api instead).

2016-11-01 20:53 UTC, wolfdancer commented
@VinnyQ nice!  I am checking it out now.

2016-11-02 18:20 UTC, wolfdancer requested changes

2016-11-02 19:21 UTC, VinnyQ commented on grafana-cloud-metrics.yaml
>  heat_template_version: 2013-05-23
no that's the heat template version we're using.  Apparently they versioned template syntax by date.

2016-11-02 19:33 UTC, wolfdancer commented on grafana-cloud-metrics.yaml
>  heat_template_version: 2013-05-23
Ah.  Thanks.

2016-11-02 21:50 UTC, VinnyQ commented
@wolfdancer are you good with this PR?  If so go ahead and +1 it and I'll merge it to master.

2016-11-02 21:51 UTC, wolfdancer commented
+1 from Product Perspective.  I don't know enough to review the template code, though. :)

2016-11-02 21:59 UTC, VinnyQ commented
Np, most of the script is actually bash and shell commands, and as long as the end result matches and behave as you expected, then we're good here :)  Thanks for the +1, I am merging now.

2016-11-02 22:02 UTC, VinnyQ commented
@wolfdancer actually I don't have write access to this repo.  Either you or @goru97 or @chrishultin or @rs-randallburt will have to merge this for us.  Can one of you merge for me?  thanks!

2016-11-02 22:26 UTC, wolfdancer commented
I don't have permission to merge either :)

2016-11-02 22:28 UTC, chrishultin commented
I can go ahead and merge this in the morning.  Can either of you remind me if this needs to be pushed to the public catalog or not?

On Nov 2, 2016, at 5:27 PM, Shane Duan <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't have permission to merge either :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/rackspace-orchestration-templates/grafana/pull/23#issuecomment-258018523>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AAkkmXDUBOAeMnEQ26UHIE1tIxsBE_HDks5q6Q4zgaJpZM4KmjtW>.

2016-11-02 23:24 UTC, wolfdancer commented
Thanks @chrishultin.  

By pushing to the public catalog you meant the heat templates available for all cloud accounts out of the box, right?  If so this has not been pushed there (we would love it though). :)

At the moment, it is still a custom template that user needs to create.

2016-11-03 15:05 UTC, merged

2016-11-03 15:07 UTC, chrishultin commented
I've gone ahead and merged.

2016-11-03 17:09 UTC, wolfdancer commented
Thanks!